language: node_js
node_js:
    - '8'
    - '10'
    - '11'
before_install:
    - if [[ `npm -v` != 6* ]]; then npm i -g npm@6; fi
    - npm install doxdox -g
after_success:
    - npm run test:docs
sudo: false
